first:
  ID: 5
  Return_Delay_Time: 250
  #Operating_Mode: 3
  # Profile_Acceleration: 0
  # Profile_Velocity: 10
  # #Position_I_Gain: 0
  # #Position_P_Gain: 50
  # Velocity_I_Gain: 1920
  # Velocity_P_Gain: 850
second:
  ID: 6
  Return_Delay_Time: 250
  #Operating_Mode: 3
  # Profile_Acceleration: 0
  # Profile_Velocity: 10
  # #Position_I_Gain: 0
  # #Position_P_Gain: 50
  # Velocity_I_Gain: 1920
  # Velocity_P_Gain: 850
third:
  ID: 4
  Return_Delay_Time: 250
  # Operating_Mode: 3
  # Profile_Acceleration: 0
  # Profile_Velocity: 10
  # #Position_I_Gain: 0
  # #Position_P_Gain: 50
  # Velocity_I_Gain: 1920
  # Velocity_P_Gain: 850
#fourth:
 # ID: 4
  #Return_Delay_Time: 250
  #Operating_Mode: 3
  #Profile_Acceleration: 0
  #Profile_Velocity: 0
  #Velocity_I_Gain: 1920
  #Velocity_P_Gain: 850
